/* Replace with your SQL commands */

-- ALTERED USERS TABLE, ADDED NEW COLUMN USERS NAME
ALTER TABLE USERS 
ADD COLUMN USER_NAME VARCHAR(200) NOT NULL;

-- ALTERED USERS TABLE EMAIL & PASSWORD COLUMN
ALTER TABLE USERS
ALTER COLUMN EMAIL SET NOT NULL,
ADD CONSTRAINT email_unique UNIQUE (EMAIL),
ALTER COLUMN PASSWORD SET NOT NULL;




